Add get_flow_residuals and get_flow_lower_face
gwmod/nlmod pull request #327
Opened 2024-02-22 22:21 UTC by rubencalje

2024-02-26 16:09 UTC, OnnoEbbens requested changes

2024-02-26 16:09 UTC, OnnoEbbens commented on nlmod/gwf/output.py
> +        # detemine flf_index first
typo: determine

2024-02-26 16:09 UTC, OnnoEbbens commented on nlmod/mfoutput/binaryfile.py
> +def _get_binary_budget_record(fobj, ipos, header, column):
docstring?

2024-02-27 08:39 UTC, rubencalje commented on nlmod/gwf/output.py
> +        dims = ("time",) + dims
this would place time at the end of dims, and we want it at the start

2024-02-27 08:43 UTC, rubencalje commented on nlmod/gwf/output.py
> +def get_flow_lower_face(ds, kstpkper=None, grb_file=None, lays=None):
Omdat het integers zijn. layer duidt meer op de laag-naam.

2024-02-27 09:55 UTC, rubencalje commented on nlmod/gwf/output.py
> +    cbf = get_cellbudgetfile(ds)
Handled. Implemented the same logic as in `get_budget_da`

2024-02-27 09:55 UTC, rubencalje commented on nlmod/gwf/output.py
> +        # detemine flf_index first
Changed

2024-02-27 09:57 UTC, rubencalje commented
Thanks for the review. I implemented most of the requested changes. On top of that, I renamed `grbfile` to `grb_file` everywhere, as this is also the way FloPy names this variable.

2024-02-28 07:52 UTC, OnnoEbbens commented on nlmod/gwf/output.py
> +        dims = ("time",) + dims
Ah ok!

2024-03-01 15:04 UTC, OnnoEbbens approved these changes

2024-03-06 07:48 UTC, merged