Release v0.9.0
gwmod/nlmod pull request #385
Opened 2024-11-13 12:46 UTC by dbrakenhoff

2024-11-18 13:08 UTC, rubencalje commented
The NHI-GWO database does not return data for Brabant Water anymore, which is the reason this tests in the PRs was failing. I sent a mail to the NHI helpdesk, with a question why this is the case. For now, maybe we can change the test to a well field of another drinking water company, for example Vitens.

2024-11-25 11:13 UTC, OnnoEbbens requested changes
Some comments from me, I can also fix them if you want.

2024-11-25 11:13 UTC, OnnoEbbens commented on nlmod/read/bgt.py
> +    bgt_bronhouder_names = {
I would prefer to put 300 lines of data in a separate data file not in a function

2024-11-25 11:13 UTC, OnnoEbbens commented on nlmod/version.py
> +__version__ = "0.8.2.dev0"
```suggestion
__version__ = "0.9.0"
```

2024-11-26 10:03 UTC, OnnoEbbens commented on nlmod/data/geotop/REF_GTP_LITHO_CLASS.xlsx
I see this PR message now (https://github.com/gwmod/nlmod/pull/361) and the files are only 26 kb so not something to worry about.

2024-11-26 10:04 UTC, OnnoEbbens commented on nlmod/read/bgt.py
> +    bgt_bronhouder_names = {
fixed

2024-11-26 15:04 UTC, OnnoEbbens approved these changes

2024-11-26 15:04 UTC, merged